#!/usr/bin/env bash

set -e

TAGS=("php7.4" "php8.0" "php8.1" "php8.2")
IMAGE="pnlinh/magento"
GHCR_IMAGE="ghcr.io/pnlinh/magento"

echo "Starting to push Docker images..."

for TAG in "${TAGS[@]}"; do
  echo "Pushing ${IMAGE}:${TAG}..."
  docker push "${IMAGE}:${TAG}"

  echo "Tagging ${IMAGE}:${TAG} as ${GHCR_IMAGE}:${TAG}..."
  docker tag "${IMAGE}:${TAG}" "${GHCR_IMAGE}:${TAG}"

  echo "Pushing ${GHCR_IMAGE}:${TAG}..."
  docker push "${GHCR_IMAGE}:${TAG}"
done

echo "All images pushed successfully!"
